### ISSUE TITLE
using a Hash instead of an an Array for Response#errors

### ISSUE THREAD

**Issue by alperkokmen** [SAML-Toolkits/ruby-saml#303]
at the moment `Response` object uses an `Array` (initialized [here](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L42)) to keep track of errors encountered during validation.

at the moment, it's very human-friendly – i.e. if you wanted to display errors to users, you could just consume `errors` in your controller after `is_valid?` check and be done. however, i think it would be better for programmatically traversing errors and making sense of them if `errors` was a `Hash`.

easiest pattern i can think of is to leverage the suffix for each `validate_XXX` method. e.g.

``` ruby
def validate_num_assertion
  # validation fails...
  append_error(:num_assertion, "SAML Response must contain 1 assertion")
end

def validate_destination
  # validation fails...
  append_error(:destination, "The response was received at #{destination} instead of #{settings.assertion_consumer_service_url}")
end
```

obviously, this would be a breaking change; but, i think `errors` could be declared as _deprecated_ and a `Hash` named `errors_hash` could be defined as a start to allow people upgrade easily. until deprecated `error` arrays is completely removed, `errors` and `errors_hash` could work side-by-side.

**repo owners**, i would appreciate if you could let me know if this makes sense. if it does, i am open to taking a first stab at it with a pull request.

**Comment by pitbulk** [comment]
That makes sense but we need to implement a solution that not break current environments.

**Comment by johnnyshields** [comment]
@alperkokmen (or anyone else), I think the right way to do this would be to make a global config option that toggles between the old way and the new way. PR would be welcome here.

**Comment by johnnyshields** [comment]
Marking this as "Won't Fix" it will break to many things, but also there's an easy solution here.

You can just `.to_h` on a Array of 2-tuples (which the `errors` currently is) and it will convert it to a Hash. The only downside is if the same key appears twice, it will be overwritten. I'm not sure whether this happens.
