### ISSUE TITLE
Failing security verifications from http://saml.oktadev.com/ about time bound conditions

### ISSUE THREAD

**Issue by jhubert** [SAML-Toolkits/ruby-saml#417]
I just tested our SAML security using the verification tool at http://saml.oktadev.com/ and 3 of the checks are failing:

![image](https://user-images.githubusercontent.com/3384/30553880-669c6042-9c57-11e7-89fe-4e1e004e8d79.png)

I checked the SAML 2.0 spec and it seems that ruby-saml is accurate in that the lack of a time bound condition means that the assertion is valid.

At the same time, it seems that being able to modify the SAML Response should render it invalid so that those tests fail. 

Any idea what I should look for to figure out what I'm doing wrong? Is this something other people have experienced?

**Comment by pitbulk** [comment]
NotBefore and NotOnOrAfter are optional attributes, they can be omitted and that does not invalidates the SAMLResponse.

```
<attribute name="NotBefore" type="dateTime" use="optional"/>
<attribute name="NotOnOrAfter" type="dateTime" use="optional"/>
```

```
2.5.1.2 Attributes NotBefore and NotOnOrAfter
The NotBefore and NotOnOrAfter attributes specify time limits on the validity of the assertion within
the context of its profile(s) of use. They do not guarantee that the statements in the assertion will be
correct or accurate throughout the validity period.
The NotBefore attribute specifies the time instant at which the validity interval begins. The
NotOnOrAfter attribute specifies the time instant at which the validity interval has ended. [E92] As
noted in section 1.3.3, relying parties SHOULD allow for reasonable clock skew in the interpretation of
both values.
If the value for either NotBefore or NotOnOrAfter is omitted, then it is considered unspecified. If the
NotBefore attribute is unspecified (and if all other conditions that are supplied evaluate to Valid), then
the assertion is Valid with respect to conditions at any time before the time instant specified by the
NotOnOrAfter attribute. If the NotOnOrAfter attribute is unspecified (and if all other conditions that
are supplied evaluate to Valid), the assertion is Valid with respect to conditions from the time instant
specified by the NotBefore attribute with no expiry. If neither attribute is specified (and if any other
conditions that are supplied evaluate to Valid), the assertion is Valid with respect to conditions at any
time.
If both attributes are present, the value for NotBefore MUST be less than (earlier than) the value for
NotOnOrAfter.
```
ruby-saml [validates](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L664) NotBefore and NotOnOrAfter when they are present.


I don't know how the tool that you are using works, but if you modify the SAMLResponse in some way, the signature validation should fail. If it doesn't fail, that means that maybe the tool re-sign after the manipulation.




Reference:
https://www.oasis-open.org/committees/download.php/56776/sstc-saml-core-errata-2.0-wd-07.pdf
(Page 22 and 24)
