### ISSUE TITLE
Many Attribute Services

### ISSUE THREAD

**Issue by davidlibrera** [SAML-Toolkits/ruby-saml#466]
I noticed that the current implementation of ruby-saml allow to insert into metadata just only one
```<md:AttributeConsumingService />```
 https://github.com/onelogin/ruby-saml/blob/b0301c9da6c5c1674c29a8544c9e32d153bdbcca/lib/onelogin/ruby-saml/settings.rb#L28
 while [SAML specification for Metadata](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf), at line 752 allow the presence of many attributes sets.

It could make sense to change this behaviour in order to enable ```ruby-saml``` gem to do this?

**Comment by pitbulk** [comment]
Is true that the spec allows to register [more than 1 AttributeConsumingService](http://www.datypic.com/sc/saml2/e-md_SPSSODescriptor.html).

But to simplify the settings, we implemented the ability to only register one service.
