### ISSUE TITLE
OneLogin::RubySaml.format_cert break a cert with comment

### ISSUE THREAD

**Issue by cyc115** [SAML-Toolkits/ruby-saml#513]
`OneLogin::RubySaml.format_cert` strips out the `BEGIN` and `END` line then remove line breaks. This will break any cert with prefix and suffix comments like the example below:
```
comment
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
comment
```

The formatted certificate will be:
```

-----BEGIN CERTIFICATE-----
comment
[...]
comment
-----END CERTIFICATE-----
```
see:
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/utils.rb#L51

**Comment by pitbulk** [comment]
Why you have comments on the certs?

**Comment by cyc115** [comment]
I forgot exactly which openssl command I run to generate the pem file but at least with some options openssl will generate cert with the human readable format prefixing the `-----BEGIN CERTIFICATE-----`. 

I don't have a PR but am willing to write one if there's interest in this.

**Comment by pitbulk** [comment]
Duplicated of #636. Will leave the other one open and close this one.
