### ISSUE TITLE
Different certificates (and private keys) for SP signing and encryption

### ISSUE THREAD

**Issue by pavolzbell** [SAML-Toolkits/ruby-saml#560]
Hello, I am facing an IDP who requires different certificates (and private keys) for singing and encryption. Is it possible to configure my SP in such way with this gem?

**Comment by pitbulk** [comment]
Right now at the toolkit you can only register
- 1 IdP public cert
- 1 SP public cert and SP private key.

The toolkit publishes the same public cert to allow the IdP to validate Signatures generated by the SP as well as encrypt the SAML Assertions.

Are you sure you are not able to import the generated SP Metadata XML on the IdP side?

**Comment by pavolzbell** [comment]
@pitbulk yes, I am absolutely sure that we need different SP certificates and private keys for singing and encryption as this is both required and then verified by the IDP.

**Comment by pitbulk** [comment]
What software is used on the IdP side?
I 'm not aware of this kind restriction of restriction in the SAML standard.

The toolkit right now does not support registering different pairs to sign and decrypt

**Comment by pavolzbell** [comment]
I am not sure what kind of software is on the IDP side and it is not relevant as this is a new restriction placed by Slovak eGov (slovensko.sk) IDP. It will take effect in the upcoming months. In other words we can not do anything about it but obey.

Here is a part of the related docs:

<img width="784" alt="Screenshot 2021-01-27 at 23 15 33" src="https://user-images.githubusercontent.com/1657389/106061427-ad8ec100-60f5-11eb-8004-d9f3d860640a.png">

The last (highlighted) sentence translates to "Certificate in SP SAML metadata used for encryption must be different from certificate used for signing."

I have verified this with them (twice) and they will simply not register an SP metadata with the same certificates.

**Comment by pitbulk** [comment]
I see

P.S Strange that in page 20 appears a screenshot of the regsitered SP and only appears 1 certificate

**Comment by pavolzbell** [comment]
> P.S Strange that in page 20 appears a screenshot of the regsitered SP and only appears 1 certificate

Well, the docs are always with some mistakes in this case, but there has been an online workshop addressing this and other upcoming changes, so it is absolutely legit.

**Comment by pavolzbell** [comment]
@pitbulk anyway, are you willing to accept a PR on this issue? I think we can manage to prepare one in the near future.

**Comment by pitbulk** [comment]
It depends on how you can implement it and how much complexity will add to the toolkit.

**Comment by johnnyshields** [comment]
:+1: I also encountered this. This is important to be able to implement key rotation on the SP side.

The requirement should be:
1. Multiple encryption AND
2. Multiple signing certs
3. Each cert having its own private key specific to that cert

Currently, RubySaml implements multiple certs on the IdP side using the `idp_cert_multi` setting. This is a hash in the format:

```
setting.idp_cert_multi = { encryption: [cert1, cert2], 
                           signing: [cert3, cert4] }
```

I would like to propose we add `sp_cert_multi`, however, we also need to add in the private keys. So perhaps it could look like this:

```
setting.sp_cert_multi = { encryption: [ { cert: cert1, private_key: pk1 }, { cert: cert2, private_key: pk2 } ], 
                          signing: [ { cert: cert3, private_key: pk3 }, { cert: cert4, private_key: pk4 } ] }
```

Thoughts / comments?

**Comment by pitbulk** [comment]
I see the use cases different.

At the SP side, we support multiple IdP's certs in order to be able to validate the Signature of the SAMLResponse. Some IdPs support multiple private_ley/certs at the same time, so the scenario of supporting multiple makes sense not only in the cert rotation scenario.

The key rotation on ruby SAML was implemented in a very easy way.

When there is a new private_key/public cert to be used, the public cert is added as 
certificate_new setting. Then all IdPs have time to update its metadata and register the new cert.
After that, once all IdPs are updated, SP admin only needs to move the certificate_new value on certificate and remove the certificate_new setting and at the same time, update the new private_key value.  That way, we don't have any interruption on the service.

I don't see the need of a sp_cert_multi/sp_private_key_multi strategy here

**Comment by johnnyshields** [comment]
> I don't understand the requirement from the slovensko.sk IDP requiring 2 different SP certs involved on the signature validation and the encryption process, to be honest. There is no other SAML profile with this kind of requirement. See saml2int

The fact that SAML allows different signing and encryption certs, however silly it may be in practice, still means we ought to support it.

**Comment by jsuchal** [comment]
Here is another reason why this should be supported.

https://ec.europa.eu/cefdigital/wiki/download/attachments/82773108/eIDAS%20Cryptographic%20Requirement%20v.1.2%20Final.pdf?version=2&modificationDate=1571068651805&api=v2 

![image](https://user-images.githubusercontent.com/26342/145797378-484e8c84-854c-4688-871c-fc0a67f7403e.png)

**Comment by johnnyshields** [comment]
@pitbulk any further thoughts on this?

**Comment by johnnyshields** [comment]
@pavolzbell @jsuchal I've implemented this here: https://github.com/SAML-Toolkits/ruby-saml/pull/673

I've added lots of test cases so I'm fairly confident in it. Please try it out.

**Comment by ducthien1490** [comment]
@johnnyshields : My project also needs signing/encryption certificates, when will it release?

**Comment by johnnyshields** [comment]
@ducthien1490 you can use my branch here. The merge/release is up to @pitbulk as the project maintaier.

**Comment by pitbulk** [comment]
I plan to add this on next release.
