### ISSUE TITLE
Inconsistent Treatment of NameIDFormat by RubySaml::Settings Causing Validation Errors

### ISSUE THREAD

**Issue by joshIsCoding** [SAML-Toolkits/ruby-saml#628]
We, a service provider, are experiencing issues with identity providers who stipulate supported NameID formats in their metadata. These supported formats are incorrectly being treated as Name ID Policies of ours (as a SP) in our initiating SAML requests. For these users, a validation error of the form `OneLogin::RubySaml::ValidationError, The status code of the Response was not Success, was Requester => InvalidNameIDPolicy` is the result, blocking their use of SSO with our system. 

In the Settings module of RubySAML, you list `name_id_format` as [a Service Provider setting](https://github.com/onelogin/ruby-saml/blob/292aaccf8b39efb4d8fca557f662ca8d61290709/lib/onelogin/ruby-saml/settings.rb#L50). If, however, [as documented](https://github.com/onelogin/ruby-saml#the-initialization-phase), a request/response-agnostic approach is used for the generation of SAML Settings and the IDP Metadata Parser is used, the first stipulated NameIDFormat from the IDP metadata is extracted as a settings attribute, and the `RubySaml::Authrequest` builder interprets it in the settings object as a `NameIDPolicy` instead.

To express this another way, please see the following flow:

1. IDP provides metadata that lists supported NameID formats.
2. The RubySAML IDP Metadata parser extracts the first supported format and returns it as as a key-value setting `name_id_format: 'the first given format'`. This is passed to the SAML Settings object on initialisation.
3. The RubySAML Authrequest builder applies this IDP NameIDFormat from the settings as a SP NameIDPolicy.
4. The response fails because the provided NameIdFormat doesn't match this unintended policy.

This is a significant blocker for us and seems to be rooted in an inconsistency in how NameID formats are treated by the gem. I can't see anything in the API that would elegantly allow the IDP's name ID formats to be ignored when generating our SAML requests. In your documentation, you avoid the problem by repeatedly overriding the NameIDFormat to the 'email' type. I believe there should be a better mechanism to remove this attribute from the IDP metadata parsing, either by default or on demand. Alternatively, some clarity on this in the documentation would be much appreciated.

**Comment by joshIsCoding** [comment]
Hi Pitbulk, thanks for the reply. Forcing 'unspecified' should work as a workaround then. But I think our problem still stands as a potential issue for the gem.

The problem, in principle, is that supported NameID formats by the IdP should not define the NameID policy of the Service Provider. In practice, the parser takes the arbitrary first format from the list of supported IP formats - this is in no way guaranteed to be the one that the IdP chooses to use. So if an IdP's metadata lists persistent, email and transient types in that order, and they choose to use 'email' or the NameID, the SAML response would fail with the validation error I described, because a NameID policy stipulating 'persistent' has been unwittingly defined in the request.

**Comment by pitbulk** [comment]
Are you connecting 1 SP with multiple IdPs at the same time?

The toolkit was desgined to work as 1 SP - 1 IdP.  Is true that the NameID Format param could be considered as a parameter of the IdP, but the decision taken when the toolkit was implemented was that this specific value is the one that gonna be used at the SP level in order to build the AuthNRequest.

If you use the same SP section of the settings for all your connections with multiple IdPs, I agree that the value of the NameID Format cant be the same for all of them, in the same way that the security parameters should be changed as well (one IdP could require the AuthNRequest to be signed and other not).

So if you are reading the parameters from a database or something and building the toolkit settings dinamically, consider at the database level to store a NameID Format supported at the IdP and later inject such value on the SP NameID Format field (and by default, consider to use the unspecified.

**Comment by joshIsCoding** [comment]
Thanks for the explanation. You're right that we are connecting with multiple IDPs, via OmniAuth SAML and OmniAuth Multi-provider. Considering that the toolkit was designed for 1-to-1 relationships, I accept that its current functionality is less problematic than it first seemed and can close this issue. I would argue, though, that this behaviour is somewhat unclear, and that some users might avoid stipulating their own nameID format, instead parsing their IdPs metadata - in which event this issue would present itself. Would it be helpful if this behaviour were documented? I can submit a pull request for the readme if you like.

**Comment by pitbulk** [comment]
Sure, share your improvements to the readme and I will review.
