### ISSUE TITLE
Update Readme how to use parser's options

### ISSUE THREAD

**Issue by ksrnnb** [SAML-Toolkits/ruby-saml#654]
I have started to use this library but it was difficult to understand how to use parser's options.
For example, when multi name_id_formats are given by idp metadata, I didn't know how can I confirm idp supports persistent format.

I found this [PR](https://github.com/SAML-Toolkits/ruby-saml/pull/614/files#diff-7ccf4572f58fe729fbeec91f8a3c11b99cab3e64bdfb3da871e658d6e0f0dbfeR128-R130), so I know how to use options now, but it is difficult for beginner to know how to use parser's options.
I think it should be written in README.

**Comment by pitbulk** [comment]
Hi @ksrnnb do you want to contribute to the README?

**Comment by ksrnnb** [comment]
Yes. I'll change 2 points as bellows. Is it seem good?

## update [Retrieve one Entity Descriptor when many exist in Metadata](https://github.com/SAML-Toolkits/ruby-saml#retrieve-one-entity-descriptor-when-many-exist-in-metadata)
  - Add `name_id_format`, `sso_binding` and `slo_binding` to options.
```ruby
  validate_cert = true
  options = {
    entity_id: "http//example.com/target/entity",
    name_id_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
    sso_binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
    slo_binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
  }
  settings = idp_metadata_parser.parse_remote(
               "https://example.com/auth/saml2/idp/metadata",
               validate_cert,
               options
             )
```
## fix [Validating Signature of Metadata and retrieve settings](https://github.com/SAML-Toolkits/ruby-saml#validating-signature-of-metadata-and-retrieve-settings)
syntax highlight is not work. so, I'll fix it.

**Comment by pitbulk** [comment]
Better add a new Entry instead replace "[Retrieve one Entity Descriptor when many exist in Metadata"

For example:  "Retrieve one Entity Descriptor with an specific binding and nameid format when many exist in Metadata"
And then add your example

**Comment by ksrnnb** [comment]
I have created a PR, please check it.
