### ISSUE TITLE
Remove OneLogin namespace (in a major version upgrade)

### ISSUE THREAD

**Issue by johnnyshields** [SAML-Toolkits/ruby-saml#659]
I propose that we remove the `OneLogin` root namespace in a major version upgrade, perhaps we do it in 2.0. The root namespace should be `RubySaml`. It seems OneLogin is no longer the sponsor of the project.

**Comment by pitbulk** [comment]
As I mentioned in the PR, I don't see a real benefit for removing OneLogin from the namespace.

**Comment by NathanZookCH** [comment]
I think the obvious solution is `OneLogin = Object`, and turn onelogin into a simlink to `..`.  That can be a minor version upgrade, and a deprecation notice can say that this declaration will go away in 2.0.
