### ISSUE TITLE
ruby toolkit sample code has incorrect module name

### ISSUE THREAD

**Issue by fastjames** [SAML-Toolkits/ruby-saml#665]
I tried to figure out how to submit this via the developers site but I could not find a way to do it, so this is the best I can do.

On https://developers.onelogin.com/saml/ruby , the page includes a sample `saml_controller.rb` file. On lines 9 and 13 of that file, classes are referenced as follows:

```
Onelogin::RubySaml
```

The module hierarchy should be
```
OneLogin::RubySaml
```

**Comment by pitbulk** [comment]
Sorry I don't have any control on https://developers.onelogin.com/saml/ruby
