### ISSUE TITLE
Add `base64` gem dependency for Ruby 3.4 compatibility

### ISSUE THREAD

**Issue by casperisfine** [SAML-Toolkits/ruby-saml#680]
I wanted to submit a PR but was a bit surprised with the gemspec and wasn't sure how to add a dependency in it.

So just a quick heads up that Ruby 3.4 will make `base64` a "bundled gems", meaning gems now need to declare their dependency on it: https://bugs.ruby-lang.org/issues/20187

**Comment by dentarg** [comment]
Trying to simplify the gemspec in https://github.com/SAML-Toolkits/ruby-saml/pull/681

Since https://github.com/SAML-Toolkits/ruby-saml/commit/9b6e3e92dc21dd62439ebd63df722b6ffd43e391 the required Ruby version for ruby-saml is effectively Ruby 2.6.

**Comment by johnnyshields** [comment]
I've fixed this here. It will be for version 2.0 only.

**Comment by johnnyshields** [comment]
Done on v2.0
